### ISSUE TITLE
Running this on a OSX

### ISSUE THREAD

**Issue by naveensrinivasan** [scratch2mcpi/scratch2mcpi#1]
How do we run this on a mac osx? 

Thanks

**Comment by pbierhoff** [comment]
This has been written specifically to work with the Raspberry Pi version of Minecraft (MCPI). As such, you cannot run this on a MAC OSX.

**Comment by champierre** [comment]
Actually you can with CraftBukkit server and RaspberryJuice plugin.

English resource:
http://www.stuffaboutcode.com/2013/06/programming-minecraft-with-bukkit.html

This is step by step procedure demonstrated in YouTube video, but it is in Japanese.(Maybe automated English caption might help)
https://www.youtube.com/watch?v=y4X3m4m9J_A
https://www.youtube.com/watch?v=0PmUlsufwps

**Comment by pbierhoff** [comment]
Alright I should have been clearer. Without additional effort it won't work. There is a book called [Adventures in Minecraft](http://www.amazon.com/Adventures-Minecraft-David-Whale/dp/111894691X) which explains how to set up the Minecraft/Bukkit/RaspberryJuice connection in English. Just note that this is based on CraftBukkit, which is no longer available for download. You'd have to build a Spigot server and do some tweaks to get this to work. THEN you need to connect Scratch2MCPI (assuming no modifications are needed to make this run).

**Comment by champierre** [comment]
Closed
